### ISSUE TITLE
Information updated on HackMD

### ISSUE THREAD

**Issue by davy-tw** [holishing/bbslist#1]
Hey, I updated some information about bbs sites in TCFSH on HackMD note, and also add `wss://` url on them.
Should we add some client that supports `ssh://` and `ws://`/`wss://` url like: [PCMan Beta 9.5.0](https://github.com/pcman-bbs/pcman-windows/releases/tag/v9.5.0-beta) and [clyang's Welly](https://github.com/clyang/welly/releases)?

**Comment by holishing** [comment]
Sounds Great!
We can try to add more information of BBS Clients

**Comment by holishing** [comment]
This part is initially done, details need to be checked.
