### ISSUE TITLE
台中教育大學柳岸咖啡館已無復站希望

### ISSUE THREAD

**Issue by caasi** [holishing/bbslist#4]
前年看到此列表後去信問過計算機中心，回覆如下，留個紀錄：

![2019-02-02 04 04 12](https://user-images.githubusercontent.com/1164470/52146886-0ad70f80-26a0-11e9-8b43-9699b2d61d74.png)

另外柳岸是從某個舊版本的 Maple-itoc 改的，那時並未使用版本管理工具。

**Comment by holishing** [comment]
瞭解感謝回覆，之後會統一作確認，若可行也麻煩至 HackMD 作修改了，感謝！

--
* 註: 資訊往後於這個 repo 統一更新完後再 close 這個 issue

**Comment by caasi** [comment]
已至 HackMD 增加資訊，感謝你整理這張表！
