### ISSUE TITLE
沈澱日記

### ISSUE THREAD

**Issue by simbafs** [holishing/bbslist#9]
沈澱日記近日恢復營運
但是連線只開放 25 port ssh 連線
`ssh -p 25 bbsu@bbs.ckcsc.net`
與網頁版 https://bbs.ckcsc.net
軟體：ptt https://github.com/ptt/pttbbs

**Comment by holishing** [comment]
這樣改可以嗎? 另外，之後也可以自行前往 HackMD 修改

**Comment by simbafs** [comment]
我們沒有開放 ws 連線（我不會弄 QAQ），只有 ssh 和網頁直連（我是用 ttyd）

**Comment by holishing** [comment]
瞭解

這邊有 websocket 設定教學可以參考：https://github.com/ptt/pttbbs/wiki/wsproxy
畢竟你現在用的方法會讓所有人的發文 ip 都是 127.0.0.1 XD，雖然你的 web server 可能還是查得到 log

**Comment by holishing** [comment]
先這樣，如果有要修正的部分麻煩再到 HackMD 修改

**Comment by simbafs** [comment]
感謝，但是我只等等到學測完再弄了

**Comment by holishing** [comment]
辛苦了 :)

**Comment by holishing** [comment]
你們的站台似乎有問題?

```
[shmget error] key = 4cc
errno = 2: No such file or directory
```

似乎是忘記 `~/bin/shmctl init` 了
